server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  servlet:
    context-path: ${SERVER_CONTEXT:/api}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5435}/${DATABASE_NAME:teleatendimento}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_VENDOR_DRIVER:org.postgresql.Driver}
    initialization-mode: embedded
    
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: com.pi.teleatendimento.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        connection.charSet: UTF-8
        types.print.banner: false
app:
  pi:
    teleatendimento:
      base-url: http://localhost:8080/api/